var indexBehaviors = function($context) {

	// bootstrap
	$('.has-tooltip', $context).tooltip();

	// animated
	$('.animate-button').on('click', function() {
		$('.animate-me').attr('class', 'animated animate-me well ' + $(this).data('animation'));
	});

	// jqueryUI
	$('.datepicker', $context).datepicker();
	$('.jquery-tabs', $context).tabs();
	$('.slider', $context).slider({
		min: 1,
		max: 500,
		slide: function(event, ui) {
			$('.slider-value').val(ui.value);
		}
	});
	$('.autocomplete', $context).autocomplete({
		source: [
			'"Scandal Makers" Narrator',
			'Abel',
			'Accountant',
			'Activist',
			'Activities Director',
			'Actor Portraying Carl Weathers',
			'Addict',
			'Adelaide',
			'Administrator',
			'Aerobics Instructor',
			'African-American Boy Inmate',
			'Agent Cummings',
			'Agent Freeling',
			'Al the Maintenance Man',
			'Alex',
			'American MP',
			'Andy Dick',
			'Andy\'s Stylist',
			'Animesh',
			'Ann Veal',
			'Announcer at Dance',
			'Announcer',
			'Annyong Bluth',
			'Anthony',
			'Argyle Austero',
			'Armstrong',
			'Army Doctor',
			'Army Sergeant',
			'Ashley Gabriel',
			'Asian Man',
			'Astronaut Lovel',
			'Auctioneer',
			'B. Lake',
			'Babies Having Babies crew',
			'Bad Guy Boat Driver',
			'Bailiff',
			'Baker',
			'Balboa Guard Carl',
			'Baliff',
			'Band Leader',
			'Bank Manager',
			'Bar Patron',
			'Barbara',
			'Barrista',
			'Barry Zuckerkorn',
			'Barry\'s Girlfriend',
			'Bartender',
			'Batter',
			'Beatrix Hebberly-Sneed',
			'Bed Patient',
			'Ben',
			'Bernardo',
			'Beth Baerly',
			'Betty the Church Official',
			'Billy Crystal Meth',
			'Bingo Announcer',
			'Birthday Party Man',
			'Birthday boy',
			'Bix',
			'Blue Man',
			'Bluth Company Employee',
			'Bluth Employee',
			'Board Member',
			'Bob Loblaw',
			'Bob',
			'Boy Gentles',
			'Brian Grazer',
			'Brian Snee',
			'Brian',
			'Bride of Gob',
			'Bully',
			'Bus Driver',
			'Bus Passenger',
			'Buster Bluth',
			'CIA Agent Bum',
			'Cab Driver',
			'Cal Cullen',
			'Candida',
			'Car Salesman',
			'Carl Weathers',
			'Carla',
			'Carlos',
			'Carpenter',
			'Casting Director',
			'Chairman',
			'Charity Guest',
			'Charles Dawkins',
			'Charles Milford',
			'Charlotte',
			'Check Out Nurse',
			'China Garden',
			'Cho',
			'Chona',
			'Chorizo Salesman',
			'Chris Kazmierczak',
			'Chuck the Canadian',
			'Cindi Lightballoon',
			'Clerk',
			'Clinic Supervisor',
			'Coach Jerry',
			'Coast Guardsman',
			'Coco',
			'Colonel B. Arthur',
			'Colonel Grimm',
			'Colonel Smalls',
			'Conan O\'Brien',
			'Congressman John Van Huesen',
			'Construction Worker',
			'Cosmetology Instructor',
			'Country Club Manager',
			'Country Club Waiter',
			'Cowboy Waiter',
			'Crab Shack Worker',
			'Crow T. Robot',
			'Dancer',
			'Dave Williams',
			'David Henrie',
			'David the Aide',
			'Dean Fleer',
			'Deann',
			'Debrie Bardeaux',
			'Dee',
			'Dentist',
			'Derek',
			'Derrin the Guard',
			'Detective Fellows',
			'Detective Munch',
			'Detective Smee',
			'Detective Streudler',
			'Diego Villalobos',
			'Disgusted Bluth Employee',
			'Doctor Carr',
			'Doctor Norman',
			'Documentary Filmmaker',
			'Donna',
			'Doug Fleer',
			'Doug',
			'Dr. Farmer',
			'Dr. Hate',
			'Dr. Miller',
			'Dr. Phil Gunty',
			'Dr. Stein',
			'Dr. Tilive',
			'Dragon',
			'Drew',
			'Drill Sergeant',
			'Drug Dealer',
			'Drug Rep',
			'EMT',
			'EMT',
			'Ealing Club Host',
			'Ealing Club Hostess',
			'Ealing Club Waiter',
			'Earl Milford',
			'Earl Samuels',
			'Earle Monroe',
			'Eblin',
			'Employer',
			'Engineer',
			'Enrique',
			'Eric Snee',
			'Everado',
			'Executive in Yurt',
			'Executive',
			'FOX Reporter',
			'Fair Patron',
			'Fake General',
			'Fantastic Four Henchman',
			'Father Marsala',
			'Federale',
			'Female Concierge',
			'Fireman',
			'Fireman',
			'Fisherman',
			'Flight Attendant',
			'Floyd the Barber',
			'Foreign Cashier',
			'Foreman',
			'Fran',
			'Frank',
			'Gary',
			'Gene Parmesan',
			'General Anderson',
			'George Bluth Sr.',
			'George Sr.\'s Love Child',
			'George-Michael Bluth',
			'Girl Lucille',
			'Girl with Low Self Esteem',
			'Girl-Michael',
			'Gob Bluth',
			'Govennah',
			'Gregory',
			'Group Leader',
			'Guard Joe',
			'Guard',
			'Guard',
			'Guard',
			'Guard\'s Daughter',
			'Guitarist',
			'Gun Vendor',
			'Gunner',
			'Guy in Shuttle Bus',
			'Heartfire',
			'Helen Maria Delgado',
			'Herb Zuckerkorn',
			'Herbert Love',
			'Hiker',
			'Honorable Judge Reinhold',
			'Hope Loblaw',
			'Hors D\'oeuvre Server',
			'Hot Cop',
			'Hot Cops \'Jay\'',
			'Hot Sailor Bix',
			'Hotel Clerk',
			'Ian',
			'Ice',
			'Imagine Guard',
			'Indian Medical Student',
			'Intern',
			'Investor',
			'Ira Gilligan',
			'Iraqi Cab Driver',
			'Iraqi Guard',
			'Iraqi Man',
			'Iraqi Soldier',
			'Irving',
			'J. Walter Weatherman',
			'Jackie',
			'Jaideep',
			'James Alan Spangler',
			'James Carr',
			'Jan Eagleman',
			'Japanese Hostess',
			'Jaspar',
			'Javier',
			'Jay',
			'Jeff',
			'Jeff',
			'Jeremy',
			'Jeremy',
			'Jerry Bruckheimer\'s Assistant',
			'Jessie',
			'Joan Bark',
			'Joan',
			'Joe',
			'Joel Robinson',
			'John Beard Jr.',
			'John Larroquette',
			'Johnny Bark',
			'Jonah Feinberg',
			'Josh Abramson',
			'Joyce',
			'Judge Kornzucker',
			'Judge Lionel Ping',
			'Judge',
			'Judge',
			'Juggler',
			'Julius',
			'Junkie',
			'Kabir',
			'Kitty Sanchez',
			'Lance',
			'Larry',
			'Lem',
			'Lindsay Bluth Fünke',
			'Lionel',
			'Lionel\'s Mom',
			'Little Justice',
			'Local Man',
			'Loretta',
			'Lorna Hawker',
			'Love Security Guard',
			'Love Security Guard',
			'Lucille Austero',
			'Lucille Bluth',
			'Luisa Velez',
			'Lupe',
			'Lupe\'s Brother',
			'Lupe\'s Uncle',
			'Lupus Sufferer',
			'Luz',
			'Lynda the Producer',
			'Maeby Fünke',
			'Maggie Lizer',
			'Maggie',
			'Magician',
			'Maitre d\'',
			'Maitre\'D',
			'Make Up Artist',
			'Man 1',
			'Man',
			'Man',
			'Man',
			'Marauder',
			'Marco Villalobos',
			'Marcus',
			'Mario',
			'Mario',
			'Mark Cherry',
			'Marky Bark',
			'Marla',
			'Marta Estrella',
			'Matire d\'',
			'Memo',
			'Mercado Salesman',
			'Mexican Warden',
			'Michael Bluth',
			'Mike Dawkins',
			'Military Officer',
			'Monti',
			'Mort Meyers',
			'Mort\'s Assistant',
			'Moses Taylor',
			'Mother\'s Boy',
			'Motherboy Member',
			'Movie Passerby',
			'Movie Patron',
			'Mrs. Astronaut Lovel',
			'Mrs. Oh',
			'Mrs. Van Skoyk',
			'Mrs. Veal',
			'Narrator',
			'Nazhgalia',
			'Nellie',
			'Newscaster',
			'Noh',
			'Note-taking Indian Medical Student',
			'Nurse Janice',
			'Nurse',
			'OC Nurse',
			'OPIE Awards Attendee',
			'Oakwood',
			'Office guy',
			'Officer Carter',
			'Officer Kelley',
			'Officer Taylor',
			'Old Woman',
			'Olive Garden',
			'Ophelia',
			'Optometrist',
			'Paramedic',
			'Paramedic',
			'Partier',
			'Pastor Veal',
			'Patient',
			'Patient\'s Mother',
			'Paul \'P-Hound\' Huan',
			'Perfecto Telles',
			'Person',
			'Pete the Mailman',
			'Peters',
			'Phillip Litt',
			'Photographer',
			'Pitch Man',
			'Police Officer',
			'Polygraph Technician',
			'Pre-School Mom',
			'Priest',
			'Prison Guard',
			'Prisoner in the Yard',
			'Prisoner',
			'Process Server Bum',
			'Process Server',
			'Proctologist',
			'Proctor',
			'Prosecuting Attorney',
			'Protestor',
			'Protestor',
			'Publicist',
			'Quatro de Cinco Reveler',
			'Rally Member',
			'Raphocwcps Narrator',
			'Rav Nadir',
			'Ray',
			'Rebel Alley',
			'Receptionist',
			'Red-Headed Boy',
			'Resident',
			'Reunion Dad',
			'Rev. Bob Patterson',
			'Reveler',
			'Reveler',
			'Richard Shaw',
			'Rita',
			'Rocky Richter',
			'Roger Danish',
			'Rolando',
			'Rollo',
			'Rosalita',
			'Rose',
			'Saddam Hussein',
			'Saddam',
			'Sailor Boy',
			'Saleswoman',
			'Sally Sitwell',
			'Scarlet Letterman',
			'Scarlett Letterman',
			'Security Guard',
			'Security Guard',
			'Sergeant Baker',
			'Sergeant Briggs',
			'Sergeant Melnick',
			'Shannon Ryan',
			'Shannon',
			'Shepherd',
			'Sheriff Jessop ',
			'Sheriff',
			'Sheriff',
			'Sitwell Secretary',
			'Skateboard Kid',
			'Skateboarder',
			'Soldier',
			'Soldier',
			'Spa Employee',
			'Spring Breaker',
			'Spring Breaker',
			'Spring Breaker',
			'Stage Hand',
			'Stage Manager',
			'Stan Sitwell',
			'Starla',
			'Starsky',
			'Steve Holt',
			'Storage Auctioneer',
			'Storage Dave',
			'Store Owner',
			'Street Vendor',
			'Stripper',
			'Student',
			'Student',
			'Student',
			'Stylist',
			'Supervisor Spoon',
			'Supervisor',
			'Supervisor\'s Daughter',
			'Surgeon',
			'Suspect',
			'Swallows Manager',
			'T-Bone',
			'TSA Agent',
			'Tango',
			'Teacher',
			'Ted',
			'Teen Buster',
			'Teen Lindsay',
			'Teen Magician',
			'Teen Sally',
			'Teen',
			'Terry',
			'The D.A.',
			'The Literal Doctor',
			'Therapist Sandy',
			'Tobias Fünke',
			'Tom',
			'Tony Wonder',
			'Tourist',
			'Tracey B.',
			'Trang',
			'Trang\'s Grandfather',
			'Treat',
			'Trevor',
			'Trippler',
			'Trisha Thoon',
			'Trout',
			'Truck Driver',
			'Twin Andrew',
			'Twink',
			'US Soldier',
			'US Soldier',
			'Uncle Jack',
			'Uncle Paul',
			'Undercover Cop Kid',
			'Undercover Cop',
			'Usher',
			'Valet',
			'Veejay',
			'Veterinarian',
			'Waiter',
			'Warden James Buck',
			'Warden Stefan Gentles',
			'Waspy Girl',
			'Wayne Jarvis',
			'White Power Bill',
			'Widow Carr',
			'Woman at Country Club',
			'Woman in Chair',
			'Woman in Negligee',
			'Woman',
			'Woman',
			'Workman',
			'Wrangler Jeff',
			'Yurt Clerk',
			'\'Beautiful\' Kitty'
		]
	});

};
